### ISSUE TITLE
vscode plugin "Code Outline" displays flat list instead of a tree for qore files

### ISSUE THREAD

**Issue by pvanek** [qorelanguage/qore-vscode#5]
i works for Python etc. Maybe related to:
https://github.com/patrys/vscode-code-outline/issues/66

**Comment by omusil24** [comment]
That's because astparser module doesn't send any kind of hierarchy data and the LSP protocol doesn't even support it officially.

**Comment by pvanek** [comment]
the extension is not active anymore. Closed in favor of
https://github.com/qorelanguage/qore-vscode/issues/9
