### ISSUE TITLE
Unable to go to class definitions

### ISSUE THREAD

**Issue by turlyalz** [qorelanguage/qore-vscode#7]
%new-style
%strict-args
%require-types
%enable-all-warnings

%requires RestClient

RestClient rest("sa");

When trying to go to the RestClient class definition I'm getting the following error:

`Unable to open 'C:\qore\share\qore-modules\0.9.0\RestClient.qm': File is a directory.`

**Comment by pvanek** [comment]
Windows only. Cannot reproduce it on linux

Probably a qls.q issue

**Comment by pvanek** [comment]
Upstream maintainers gives us an info about it. It's probably a `file://` prefix issue from paths provided from qls.q.

Pure vscode based test case:

- create a new *.js file
- create a new existing text file on your filesystem
- add to the js file:

```
/**
 * file://C:\Users\pvanek\t.txt
 * file:///C:\Users\pvanek\t.txt
 */
```

try CTRL+click on the url. 1st case leads to our error, 2nd case works fine.
