### ISSUE TITLE
.qmapper files are not syntax highlighted 

### ISSUE THREAD

**Issue by sejvlond** [qorelanguage/qore-vscode#8]
It's probably because .qmapper files are specialities of qorus itself, so should we add a support here or into the https://github.com/qoretechnologies/qorus-vscode/ ?

**Comment by omusil24** [comment]
Well, `.qmapper` files are not Qore code. Maybe we could add another "language" to the qore-vscode for the qmapper files.

**Comment by pvanek** [comment]
qmapper is qorus only. Moved to https://github.com/qoretechnologies/qorus-vscode/issues/38
